spring.application.name=genesis-registration-system

# H2 databaze ulozena na disku
spring.datasource.url=jdbc:h2:file:./data/genesis-db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Hibernate vytvari tabulky a aktualizuje schema
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# H2 konzole
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# tabulky a data nejsou ulozena ve skriptu
spring.sql.init.mode=never

