spring.application.name=genesis-registration-system

# H2 databáze
spring.datasource.url=jdbc:h2:mem:genesis-db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA nastavení
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# H2 konzole
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

