spring.application.name=genesis-registration-system

# H2 databáze ulo?ená na disku
spring.datasource.url=jdbc:h2:file:./data/genesis-db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Hibernate vytvá?í tabulky a aktualizuje schéma
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# H2 konzole
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Nepou?íváme schema.sql ani data.sql
spring.sql.init.mode=never

